POST http://localhost:3003/signup
content-type: application/json

{
    "username": "migs",
    "password": "lol"
}

###

POST http://localhost:3003/signin
content-type: application/json

{
    "username": "migs",
    "password": "lol"
}
